apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.image.containerName }}
        ports:
        - containerPort: {{ .Values.image.containerPort }}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}