apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.service.clusterIPPort }}
    targetPort: {{ .Values.image.containerPort }}
    protocol: TCP
  selector:
    app: spring-boot-app
